services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: usr
      POSTGRES_PWD: pwd
      PGDATA: /data/postgres
    volumes:
      - db: /data/postgres
    ports:
      # hostPort:ctnrPort
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db:
